fixup! feat add command execution on PS1 and dublicate success history to other file

diff --git a/.shell_source/prompt_root b/.shell_source/prompt_root
--- a/.shell_source/prompt_root
+++ b/.shell_source/prompt_root
@@ -15,6 +15,80 @@ fg_lightblue='\[\e[0;94m\]'
 bg_LIGHTRED='\[\e[1;101m\]'
 reset_NC='\[\e[0m\]'
 
+# cmd execution timer (shows elapsed if > 1 min in PS1)
+_cmd_prompt_running=0
+_cmd_elapsed_str=''
+_last_exit_code=0
+_mline_buf=""
+
+# capture each readline input line (including \ continuations)
+_save_readline_ml() { [[ -n "$READLINE_LINE" ]] && _mline_buf+="$READLINE_LINE"$'\n'; }
+bind -x '"\C-x\C-r": _save_readline_ml'
+bind '"\C-m": "\C-x\C-r\C-j"'
+
+_cmd_timer_preexec() {
+    # ignore readline helper so it doesn't screw `_last_bash_cmd`
+    [[ "$BASH_COMMAND" == "_save_readline_ml" ]] && return
+    if [[ $_cmd_prompt_running == 0 ]]; then
+        _cmd_timer=${_cmd_timer:-$SECONDS}
+        _last_bash_cmd="${_last_bash_cmd:-$BASH_COMMAND}"
+    fi
+}
+
+_cmd_timer_precmd() {
+    _cmd_prompt_running=1
+
+    # log successful commands to `.bash_history_success`
+    local _nosave_re='^(PROMPT_COMMAND=|_precmd_wrapper$|\[ -n "\$force_color_prompt" \])'
+    if [[ $_last_exit_code -eq 0 && -n "$_last_bash_cmd" && ! "$_last_bash_cmd" =~ $_nosave_re ]]; then
+        printf '#%s\n%s\n' "$(date '+%s')" "$_last_bash_cmd" >> ~/.bash_history_success
+    fi
+
+    # save multiline commands to `.multiline_history`
+    # _mline_buf accumulates raw readline input lines, preserving the user's original layout
+    local _ml_trimmed="${_mline_buf%$'\n'}"
+    if [[ "$_ml_trimmed" == *$'\n'* ]]; then
+        printf '# %s [%s]\n%s\n\n' "$(date '+%F %T')" "$_last_exit_code" "$_ml_trimmed" >> "$HOME/.multiline_history"
+    fi
+
+    # execution timer: show if >= 60s, or any duration on failure
+    if [[ -n "$_cmd_timer" ]]; then
+        local elapsed=$(( SECONDS - _cmd_timer ))
+        if (( elapsed >= 60 )) || [[ $_last_exit_code -ne 0 && elapsed -ge 1 ]]; then
+            local mins=$(( elapsed / 60 ))
+            local secs=$(( elapsed % 60 ))
+            _cmd_elapsed_str="[${mins}m${secs}s]"
+        else
+            _cmd_elapsed_str=''
+        fi
+        unset _cmd_timer
+    fi
+
+    _cmd_prompt_running=0
+}
+
+_precmd_wrapper() {
+    _last_exit_code=$?
+    history -a
+    _cmd_timer_precmd
+    history -n
+    unset _last_bash_cmd
+    _mline_buf=""
+}
+
+if [[ "$TERM" =~ "screen" ]]; then
+    _debug_combined() {
+        _cmd_timer_preexec
+        set_screen_window
+    }
+    trap '_debug_combined' DEBUG
+else
+    trap '_cmd_timer_preexec' DEBUG
+fi
+
+PROMPT_COMMAND="_precmd_wrapper"
+export -n PROMPT_COMMAND
+
 if [ -n "$force_color_prompt" ]; then
     if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
         # We have color support; assume it's compliant with Ecma-48
@@ -25,7 +99,7 @@ if [ -n "$force_color_prompt" ]; then
         color_prompt=
     fi
 fi
- 
+
 if [ "$color_prompt" = yes ]; then
     PS1=" $(move_cursor_to_end_line) \`if [ \$? = 0 ]; then echo -e \"${fg_green} \xE2\x9C\x85 ${reset_NC}\"; else echo -e \"${fg_red} \xE2\x9D\x8C ${reset_NC}\"; fi\` "
     PS1+="${debian_chroot:+($debian_chroot)} ${fg_GREEN} ${fg_dimyellow}\n#----------------${reset_NC}"
@@ -41,18 +115,14 @@ if [ "$color_prompt" = yes ]; then
     PS1+="${fg_CYAN}\h${reset_NC}: "
     PS1+="${fg_LIGHTBLUE}\w${reset_NC}"
     PS1+="\n \n "
-    PS1+="${fg_LIGHTRED}\\$ ${reset_NC}"
+    PS1+="${fg_LIGHTRED}\$ ${reset_NC}"
 else
-    PS1="(\H) #-[\d] \t j=\j \u@\h: \w| "
+    PS1="(\H) #-[\d] \t \${_cmd_elapsed_str}j=\j \u@\h: \w \n |> "
 fi
- 
-unset color_prompt force_color_prompt
 
+unset color_prompt force_color_prompt
 case "$TERM" in
-xterm*|rxvt*)
-    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
-    #PS1="\`if [ \$? = 0 ]; then echo \[\e[32m\]^_^\[\e[0m\]; else echo \[\e[31m\]O_O\[\e[0m\]; fi\`${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\[\e[0;93m\]\\n#--------------------------------\[\e[0m\]\[\e[1;35m\](\H)\[\e[0m\]-\[\e[1m\]\#-[\d]\[\e[0m\] \n \[\e[22;33m\]\t\[\e[0m\] \[e[0;93m\]j=\j\[\e[0m\] \[\e[1;32m\]\u\[\e[0m\]@\[\e[1;36m\]\h\[\e[0m\]: \[\e[1;94m\]\w\[\e[0m\] \n \n \[\e[1;92m\]\$\[\e[0m\] "
-    ;;
-*)
-    ;;
+    xterm*|rxvt*)
+        PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1" ;;
+    *) ;;
 esac
